


Grundlagen_der_Mathematik:
	pdflatex Grundlagen_der_Mathematik.tex 

.PHONY: clean
clean:
	@echo "Lösche *.aux, *.log "
	@find . -type f -name '*.aux' -delete
	@find . -type f -name '*.log' -delete

#Dependencies:
#sudo apt-get install inkscape 
